import { createClient as createServiceClient } from "@supabase/supabase-js";
import { getDisplayName, type AdminClient } from "@/lib/decoded/display-name";

/**
 * The dyad's "what each of you needs to hear" phrases.
 *
 * WHAT THESE PHRASES ARE — read before writing any copy about them:
 * they are **generated by the model from a person's assessment results**, not
 * written by that person. S5's prompt asks for "5 phrases" plus "why this
 * phrase lands for THIS person", derived from their attachment style. Nobody
 * typed "I'm not going anywhere" — it's an inference from their scores.
 *
 * So copy must NEVER imply these are the partner's own words or anything they
 * told us. We promise a partner's private coaching is never shared; wording that
 * hints we're passing along something they wrote undermines exactly that promise
 * even when the data is harmless. Say the SOURCE is their relationship style.
 * (Founder correction, 2026-07-16 — the original "in their own words, from
 * their profile" was both factually wrong and privacy-alarming.)
 *
 * WHERE IT RENDERS: the pair belongs to the **compatibility report**, which only
 * exists once BOTH partners have finished (founder, 2026-07-16). The solo
 * profile shows only the reader's own list plus a pointer — never a section-
 * shaped empty promise.
 *
 * CONSENT (privacy-critical — ADR-R02, "privacy by assembly, not by RLS"):
 * `theirs` is gated at share_with_human = 'full', the same rung
 * `verifySharedAccess` uses to let a partner open the whole report page. At
 * 'full' this surfaces NOTHING the reader can't already read. A lower rung
 * ('type_compatibility' = archetype + style only) would disclose new data and is
 * a founder decision, not ours. Reads assessment_reports only — never a private
 * coaching table. Fails closed everywhere.
 */

export interface NeedToHearPhrase {
  phrase: string;
  why: string;
}

/**
 * Just enough to render a signpost — no phrases. The solo profile takes THIS,
 * not the full pair: ReportViewer is a client component, so anything handed to
 * it is serialized into the page payload. Passing the phrases there would ship
 * both people's lists to a page that renders neither.
 */
export interface DyadPointer {
  /** The invite backing this dyad — the compat report's URL segment. */
  inviteId: string;
  partnerName: string | null;
  /** The partner has a finished profile carrying S5 phrases. */
  partnerReady: boolean;
}

export interface DyadNeedToHear extends DyadPointer {
  /** The reader's own phrases (their own data — never consent-gated). */
  mine: NeedToHearPhrase[];
  /** The partner's phrases. Empty unless consent is 'full' AND they're ready. */
  theirs: NeedToHearPhrase[];
}

/** Strip the phrases, keeping only what a signpost needs. */
export function toDyadPointer(dyad: DyadNeedToHear | null): DyadPointer | null {
  if (!dyad) return null;
  const { inviteId, partnerName, partnerReady } = dyad;
  return { inviteId, partnerName, partnerReady };
}

function serviceClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) {
    console.error("[need-to-hear] Missing Supabase service-role env; skipping.");
    return null;
  }
  return createServiceClient(url, key, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

/**
 * Resolve the dyad's phrases for `viewerId`.
 *
 * Pass `inviteId` to scope to a specific dyad (the compat report, which is
 * per-invite); omit it to take the viewer's consented dyad (the solo profile's
 * pointer, which just needs to know whether the partner is ready).
 */
export async function getDyadNeedToHear(
  viewerId: string,
  opts: { inviteId?: string } = {}
): Promise<DyadNeedToHear | null> {
  const admin = serviceClient();
  if (!admin) return null;

  try {
    let query = admin
      .from("decoded_invites")
      .select("id, inviter_id, recipient_id, inviter_report_id, recipient_report_id")
      .or(`inviter_id.eq.${viewerId},recipient_id.eq.${viewerId}`)
      .eq("share_with_human", "full")
      .in("status", ["consented", "connected"])
      .is("revoked_at", null)
      .not("recipient_id", "is", null)
      .neq("recipient_email", "broadcast");

    if (opts.inviteId) query = query.eq("id", opts.inviteId);

    const { data: invite } = await query.limit(1).maybeSingle();
    if (!invite) return null;

    const viewerIsInviter = invite.inviter_id === viewerId;
    const partnerId = viewerIsInviter ? invite.recipient_id : invite.inviter_id;
    const partnerReportId = viewerIsInviter
      ? invite.recipient_report_id
      : invite.inviter_report_id;
    const myReportId = viewerIsInviter
      ? invite.inviter_report_id
      : invite.recipient_report_id;

    if (!partnerId) return null;

    const [mine, theirs, partnerName] = await Promise.all([
      loadPhrases(admin, myReportId, viewerId),
      loadPhrases(admin, partnerReportId, partnerId),
      getDisplayName(admin, partnerId),
    ]);

    return {
      inviteId: invite.id,
      partnerName,
      partnerReady: theirs.length > 0,
      mine,
      theirs,
    };
  } catch (err) {
    console.error("[need-to-hear] resolve error:", err);
    return null;
  }
}

/**
 * Load one person's S5 phrases, asserting the report actually belongs to them.
 * The ownership check is cheap and turns a future backfill bug into an empty
 * block rather than a cross-user leak.
 */
async function loadPhrases(
  admin: AdminClient,
  reportId: string | null,
  ownerId: string
): Promise<NeedToHearPhrase[]> {
  if (!reportId) return [];
  const { data: report } = await admin
    .from("assessment_reports")
    .select("sections, user_id")
    .eq("id", reportId)
    .maybeSingle();
  const row = report as { sections?: unknown; user_id?: string } | null;
  if (!row || row.user_id !== ownerId) return [];
  return extractNeedToHear(row.sections);
}

/**
 * S5 stores typed JSON in content_markdown (the v2 sections convention — see
 * ReportViewer's `parsed`). Older/partial reports may lack the key entirely, so
 * every step is defensive: a malformed section must degrade to an empty list,
 * never throw on a page the user is waiting on.
 */
function extractNeedToHear(sections: unknown): NeedToHearPhrase[] {
  if (!sections || typeof sections !== "object") return [];
  const s5 = (sections as Record<string, unknown>).S5;
  if (!s5 || typeof s5 !== "object") return [];
  const raw = (s5 as Record<string, unknown>).content_markdown;
  if (typeof raw !== "string") return [];

  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }
  if (!parsed || typeof parsed !== "object") return [];

  const list = (parsed as Record<string, unknown>).what_you_need_to_hear;
  if (!Array.isArray(list)) return [];

  return list.flatMap((item) => {
    if (!item || typeof item !== "object") return [];
    const { phrase, why } = item as Record<string, unknown>;
    if (typeof phrase !== "string" || !phrase.trim()) return [];
    return [{ phrase, why: typeof why === "string" ? why : "" }];
  });
}
