import { LEGAL_CONTACT, LEGAL_LAST_UPDATED, LEGAL_VERSION } from "@/lib/platform/legal";
import { DocMeta, EmergencyResources, LegalLink } from "./shared";

/**
 * Money Maps AI & Coaching Disclaimer (DRAFT — attorney review pending, E15.6,
 * consciously deferred with the other verticals' legal review).
 *
 * The money-specific difference from the other verticals: an explicit "NOT
 * financial, investment, or tax advice" section, and an FTC-safe "no wealth
 * outcomes" promise (MONEY_DISCOVERY.md §6). Confidentiality wording matches the
 * coach's own script. Do NOT treat as final published terms — or expose money
 * publicly — until the E15.6 review lands and the founder locks the public brand name.
 */
export default function MoneyDisclaimer() {
  const c = LEGAL_CONTACT.money;
  return (
    <article className="prose-legal">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
        AI &amp; Coaching Disclaimer
      </h1>
      <DocMeta lastUpdated={LEGAL_LAST_UPDATED} version={LEGAL_VERSION} />

      <div className="mt-10 space-y-10 text-text-secondary leading-relaxed">
        <section>
          <p>
            {c.product} is an <strong>AI money coach</strong>. It works on the
            psychology underneath your money decisions — not your bank account.
            Please understand the following before you use it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            You are talking to an AI, not a person
          </h2>
          <p className="mt-3">
            Your coach is generated by artificial intelligence. It is not a
            human, and it is not a licensed therapist, psychologist, financial
            advisor, accountant, attorney, or any other licensed professional.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            Coaching and education — not therapy or treatment
          </h2>
          <p className="mt-3">
            {c.product} is for personal growth and education about your
            relationship with money. It does not provide therapy, diagnosis,
            treatment, or mental-health care, and it is not a substitute for care
            from a qualified professional. AI responses can be wrong or
            incomplete — use your own judgment.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            Not financial, investment, or tax advice
          </h2>
          <p className="mt-3">
            {c.product} coaches the <strong>psychology</strong> of money
            decisions. It does <strong>not</strong> provide financial,
            investment, securities, tax, accounting, or legal advice, and it does
            not recommend specific investments, allocations, trades, or what to do
            with your money. For those decisions, consult a licensed financial
            advisor, accountant, or attorney. We never link to or access your
            bank or financial accounts.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            Not for emergencies
          </h2>
          <p className="mt-3">
            {c.product} is <strong>not a crisis service</strong> and is not
            monitored in real time. If you or someone else may be in danger, do
            not rely on {c.product}.
          </p>
          <EmergencyResources />
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            No guaranteed outcomes
          </h2>
          <p className="mt-3">
            We make <strong>no guarantee</strong> about any financial result —
            income, wealth, returns, or otherwise — from using {c.product}. What
            it offers is a process and a clearer relationship with money, not an
            outcome. Your use of the Service is governed by our{" "}
            <LegalLink href="/terms">Terms of Service</LegalLink> and{" "}
            <LegalLink href="/privacy">Privacy Policy</LegalLink>.
          </p>
        </section>

        <section>
          <div className="rounded-lg bg-surface-100 p-4">
            <p>
              <strong>{c.entity}</strong> ({c.product})
            </p>
            <p>
              Questions:{" "}
              <LegalLink href={`mailto:${c.supportEmail}`} external>
                {c.supportEmail}
              </LegalLink>
            </p>
            <p>Website: {c.site}</p>
          </div>
        </section>
      </div>
    </article>
  );
}
