import { LEGAL_CONTACT, LEGAL_LAST_UPDATED, LEGAL_VERSION } from "@/lib/platform/legal";
import { DocMeta, EmergencyResources, LegalLink } from "./shared";

/**
 * Relatti Terms of Service (E15.5 DRAFT — attorney review pending, E15.6).
 *
 * Grounded in directives/PRIVACY_TERMS_LIABILITY_PLAN.md §5. Nails the
 * launch-critical disclaimers: not therapy, not a crisis service, not legal
 * advice; warranty disclaimer; limitation of liability; indemnity (incl.
 * third-party data the user inputs); arbitration + class-action waiver.
 */
export default function RelattiTerms() {
  const c = LEGAL_CONTACT.relatti;
  return (
    <article className="prose-legal">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
        Terms of Service
      </h1>
      <DocMeta lastUpdated={LEGAL_LAST_UPDATED} version={LEGAL_VERSION} />

      <div className="mt-10 space-y-10 text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            1. Agreement to These Terms
          </h2>
          <p className="mt-3">
            These Terms of Service (&quot;Terms&quot;) govern your access to and
            use of the Relatti relationship-coaching service (the
            &quot;Service&quot;), operated by {c.entity} (&quot;Relatti,&quot;
            &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). By creating an
            account or using the Service, you agree to these Terms, our{" "}
            <LegalLink href="/privacy">Privacy Policy</LegalLink>, and our{" "}
            <LegalLink href="/disclaimer">AI &amp; Coaching Disclaimer</LegalLink>
            . If you do not agree, you may not use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            2. What Relatti Is
          </h2>
          <p className="mt-3">
            Relatti provides AI-powered relationship coaching. It includes
            self-assessments, an AI coach you can talk with, connection features
            for you and a partner (such as compatibility reports and shared daily
            prompts), and optional reminders. Coaching is generated by AI and is
            intended for personal growth and education.
          </p>
        </section>

        {/* The critical disclaimers */}
        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            3. Not Therapy, Not a Crisis Service, Not Professional Advice
          </h2>
          <div className="mt-3 rounded-lg border border-warning/30 bg-warning/5 p-4">
            <p className="font-medium text-text-primary">
              Please read this section carefully. It defines what Relatti is not.
            </p>
          </div>
          <ul className="mt-4 list-disc space-y-2 pl-6">
            <li>
              <strong>Not a licensed professional.</strong> Relatti is an AI
              coach, not a licensed therapist, psychologist, counselor, social
              worker, physician, or attorney. It does not provide therapy,
              couples therapy, diagnosis, treatment, or medical, mental-health,
              or legal advice, and using it does not create a therapist-client,
              medical, or attorney-client relationship.
            </li>
            <li>
              <strong>Not a substitute for professional care.</strong> The
              Service is not a replacement for professional therapy, medical
              care, or legal counsel. If you may need any of these, please
              consult a qualified professional.
            </li>
            <li>
              <strong>Not a crisis or emergency service.</strong> Relatti does
              not provide crisis intervention, is not monitored in real time, and
              cannot help in an emergency. In an emergency, use the resources
              below.
            </li>
            <li>
              <strong>AI can be wrong.</strong> AI-generated coaching may be
              inaccurate, incomplete, or inappropriate for your situation.
              Evaluate it with your own judgment and seek professional advice
              where appropriate.
            </li>
            <li>
              <strong>No guaranteed outcomes.</strong> Relationships are complex.
              We make no guarantee about any relationship, personal, or emotional
              outcome from using the Service.
            </li>
          </ul>
          <EmergencyResources />
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            4. Eligibility &amp; Accounts
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>You must be at least 18 years old to use the Service.</li>
            <li>
              You are responsible for keeping your login credentials
              confidential and for activity under your account.
            </li>
            <li>You must provide accurate information when you register.</li>
            <li>
              One person, one account. A partner participates through their own
              separate account and invitation.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            5. Acceptable Use
          </h2>
          <p className="mt-3">You agree not to:</p>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>Use the Service for any unlawful purpose.</li>
            <li>
              Rely on the Service in an emergency or as a substitute for
              professional or crisis care.
            </li>
            <li>
              Input information about other people unlawfully, or in violation of
              their rights.
            </li>
            <li>
              Use the Service to harass, abuse, threaten, or harm others, or to
              generate hateful or harmful content.
            </li>
            <li>
              Attempt to access another user&apos;s data, including a
              partner&apos;s private coaching conversations.
            </li>
            <li>
              Reverse engineer, scrape, or attempt to extract the underlying
              models, prompts, or methodology.
            </li>
            <li>Exceed usage limits designed to keep access fair.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            6. Couples Features, Consent &amp; Content About Others
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              You control what you share with a connected partner. Your
              one-on-one coaching conversations remain private from your partner;
              only data you explicitly choose to share is shared.
            </li>
            <li>
              You are responsible for information you provide about other people
              (such as a partner or child), and for providing it lawfully. See
              the <LegalLink href="/privacy">Privacy Policy</LegalLink>, Section
              7.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            7. Plans, Billing &amp; Beta
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              The Service is currently offered on a free/beta basis. Features may
              change, and the Service is provided as described in Section 11.
            </li>
            <li>
              If we introduce paid plans, we will present pricing and billing
              terms before you subscribe. Paid subscriptions will be billed
              through our payment processor, and you will be able to cancel going
              forward; we will give notice of price changes.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            8. Intellectual Property
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              <strong>Your content is yours.</strong> You retain ownership of the
              content you provide.
            </li>
            <li>
              <strong>License to operate.</strong> You grant us a limited license
              to process your content solely to provide and improve the Service
              as described in the Privacy Policy.
            </li>
            <li>
              <strong>Our content.</strong> The Service, its software, coaching
              methodology, and branding are our intellectual property. You may
              use coaching insights in your own life but may not copy or resell
              the Service.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            9. Third-Party Services
          </h2>
          <p className="mt-3">
            The Service relies on third-party providers (including AI, hosting,
            database, email, and — if you enable them — messaging providers), as
            described in our{" "}
            <LegalLink href="/privacy">Privacy Policy</LegalLink>. We are not
            responsible for the availability or policies of third-party services.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            10. Disclaimer of Warranties
          </h2>
          <p className="mt-3">
            THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS
            AVAILABLE,&quot; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
            IMPLIED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
            A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE
            SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI OUTPUT WILL BE
            ACCURATE OR SUITABLE FOR YOUR CIRCUMSTANCES.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            11. Limitation of Liability
          </h2>
          <p className="mt-3">
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, {c.entity.toUpperCase()}{" "}
            SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
            CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY LOSS ARISING FROM
            RELATIONSHIP, PERSONAL, OR EMOTIONAL DECISIONS YOU MAKE, ARISING FROM
            OR RELATED TO YOUR USE OF THE SERVICE.
          </p>
          <p className="mt-3">
            OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THE SERVICE SHALL NOT
            EXCEED THE GREATER OF THE AMOUNT YOU PAID US IN THE TWELVE (12) MONTHS
            BEFORE THE CLAIM OR ONE HUNDRED U.S. DOLLARS ($100).
          </p>
          <p className="mt-3">
            YOU ACKNOWLEDGE THAT THE SERVICE PROVIDES AI-GENERATED COACHING AND
            NOT PROFESSIONAL ADVICE, AND THAT ACTIONS YOU TAKE BASED ON IT ARE AT
            YOUR OWN RISK. SOME JURISDICTIONS DO NOT ALLOW CERTAIN LIMITATIONS, SO
            SOME OF THE ABOVE MAY NOT APPLY TO YOU.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            12. Indemnification
          </h2>
          <p className="mt-3">
            You agree to indemnify and hold harmless {c.entity} and its officers,
            directors, and employees from claims, damages, and expenses arising
            from your use of the Service, your violation of these Terms, or your
            provision of information about another person in violation of their
            rights or applicable law.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            13. Dispute Resolution &amp; Arbitration
          </h2>
          <p className="mt-3">
            Please read this section carefully — it affects how disputes are
            resolved. Except where prohibited by law, you and {c.entity} agree to
            resolve any dispute arising from these Terms or the Service through
            binding individual arbitration, and{" "}
            <strong>
              not in a class, collective, or representative action
            </strong>
            . You may opt out of arbitration within 30 days of first accepting
            these Terms by contacting us. This section does not prevent either
            party from seeking relief in small-claims court where available.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            14. Termination
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              You may stop using the Service and delete your account at any time.
            </li>
            <li>
              We may suspend or terminate access if you violate these Terms or to
              protect the Service or others.
            </li>
            <li>
              On termination, deletion of your data follows the{" "}
              <LegalLink href="/privacy">Privacy Policy</LegalLink>.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            15. Governing Law
          </h2>
          <p className="mt-3">
            These Terms are governed by the laws of the {c.governingLaw}, without
            regard to conflict-of-law principles, except that the arbitration
            provision is governed by the Federal Arbitration Act.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            16. Changes &amp; Contact
          </h2>
          <p className="mt-3">
            We may update these Terms; material changes will update the version
            and date above and, where appropriate, ask you to re-accept.
            Questions?
          </p>
          <div className="mt-3 rounded-lg bg-surface-100 p-4">
            <p>
              <strong>{c.entity}</strong> (Relatti)
            </p>
            <p>
              Email:{" "}
              <LegalLink href={`mailto:${c.supportEmail}`} external>
                {c.supportEmail}
              </LegalLink>
            </p>
            <p>Website: {c.site}</p>
          </div>
        </section>
      </div>
    </article>
  );
}
