import { LEGAL_CONTACT, LEGAL_LAST_UPDATED, LEGAL_VERSION } from "@/lib/platform/legal";
import { DocMeta, EmergencyResources, LegalLink } from "./shared";

/**
 * Relatti AI & Coaching Disclaimer (E15.5 DRAFT — attorney review pending, E15.6).
 *
 * The standing, plain-language disclaimer referenced from signup, the footer,
 * and the coach. Grounded in directives/PRIVACY_TERMS_LIABILITY_PLAN.md §5 and
 * SAFETY_ESCALATION_PROTOCOL.md §4. Confidentiality wording must match the
 * coach's own script (private from the partner is the ONLY absolute).
 */
export default function RelattiDisclaimer() {
  const c = LEGAL_CONTACT.relatti;
  return (
    <article className="prose-legal">
      <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">
        AI &amp; Coaching Disclaimer
      </h1>
      <DocMeta lastUpdated={LEGAL_LAST_UPDATED} version={LEGAL_VERSION} />

      <div className="mt-10 space-y-10 text-text-secondary leading-relaxed">
        <section>
          <p>
            Relatti is an <strong>AI relationship coach</strong>. Please
            understand the following before you use it.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            You are talking to an AI, not a person
          </h2>
          <p className="mt-3">
            Your coach is generated by artificial intelligence. It is not a
            human, and it is not a licensed therapist, psychologist, counselor,
            or medical or legal professional.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            Coaching and education — not therapy or treatment
          </h2>
          <p className="mt-3">
            Relatti is for personal growth and education. It does not provide
            therapy, couples therapy, diagnosis, treatment, or medical,
            mental-health, or legal advice, and it is not a substitute for care
            from a qualified professional. AI responses can be wrong or
            incomplete — use your own judgment.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            Not for emergencies
          </h2>
          <p className="mt-3">
            Relatti is <strong>not a crisis service</strong> and is not
            monitored in real time. If you or someone else may be in danger, do
            not rely on Relatti.
          </p>
          <EmergencyResources />
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            What&apos;s private, and what isn&apos;t
          </h2>
          <p className="mt-3">
            Your one-on-one coaching conversations are{" "}
            <strong>private from your partner</strong> — that is the one privacy
            promise we guarantee. Beyond that: your messages are processed by AI
            providers and stored securely by us, and a small internal team may
            review conversations flagged for safety. We will never tell you that
            &quot;no one can ever see this.&quot; For details, read our{" "}
            <LegalLink href="/privacy">Privacy Policy</LegalLink>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            No guaranteed outcomes
          </h2>
          <p className="mt-3">
            Relationships are complex and personal. We make no guarantee about
            any outcome from using Relatti. Your use of the Service is governed by
            our <LegalLink href="/terms">Terms of Service</LegalLink> and{" "}
            <LegalLink href="/privacy">Privacy Policy</LegalLink>.
          </p>
        </section>

        <section>
          <div className="rounded-lg bg-surface-100 p-4">
            <p>
              <strong>{c.entity}</strong> (Relatti)
            </p>
            <p>
              Questions:{" "}
              <LegalLink href={`mailto:${c.supportEmail}`} external>
                {c.supportEmail}
              </LegalLink>
            </p>
            <p>Website: {c.site}</p>
          </div>
        </section>
      </div>
    </article>
  );
}
