/**
 * The consent screen's content and version — INTEGRATION_SPRINT.md §3 / I5.5.
 *
 * ─── WHY A STANDALONE SCREEN AND NOT A CHECKBOX ──────────────────────────
 *
 * A ToS checkbox at signup is statutorily not consent in Illinois, and this
 * vertical's material is the reason the distinction bites: somebody describing a
 * near-death experience to a machine is disclosing something they have told
 * almost nobody, in a state where the law has no compliance path for an AI doing
 * anything that looks like care. So the screen is its own moment, it says what
 * this is in plain sentences, and the row it writes records which version they
 * were shown.
 *
 * ─── WHERE IT LANDS ──────────────────────────────────────────────────────
 *
 * BEFORE TURN 2, never before turn 1. EXPERIENCE §5.2 puts nothing between a
 * person and the box the first time — no account, no email, no age gate — and
 * that ordering is a product decision with a reason: the people this is for have
 * usually been handled by every system they tried to tell. The first thing that
 * happens to them here is being answered.
 *
 * ⚠️ These are pre-launch drafts, in the same state as the rest of the legal set
 * (`legal.ts`): wired, versioned and logged, pending the professional review
 * that E15.6/I11 own. They are not final published terms.
 */

/** Bump when the disclosures below change materially. Stored on every row. */
export const INTEGRATION_CONSENT_VERSION = "2026-08-13";

export interface ConsentDisclosure {
  /** Stable key, stored in `coaching_consents.disclosures` so a row says what was shown. */
  key: string;
  title: string;
  body: string;
}

/**
 * The six things I5.5 requires them to be told, in the order they matter to
 * somebody about to say the hardest thing they have ever typed.
 *
 * Written flat on purpose. Every hedge here reads as a service protecting
 * itself, and this population has met a lot of that.
 */
export const INTEGRATION_DISCLOSURES: readonly ConsentDisclosure[] = [
  {
    key: "is_ai",
    title: "This is an AI, and it is not a person",
    body:
      "Everything you read here is generated by software. Nobody is on the other end reading along in " +
      "real time. It can keep company and it can remember what you tell it, and it is still a machine.",
  },
  {
    key: "not_care",
    title: "This is coaching, and it is not care",
    body:
      "Nobody here is licensed in anything. This is not medical care and it is not a substitute for it. " +
      "If something is wrong with your body or your mind, the person who can help with that is a doctor, " +
      "and this will say so rather than take their place.",
  },
  {
    key: "no_verdict",
    title: "Nobody here will tell you what happened to you",
    body:
      "It will not tell you what your experience was, and it will not tell you it did not happen. Nobody " +
      "honest can settle that from the outside, so it says so plainly and once. The work here is the " +
      "other question: how you live with it.",
  },
  {
    key: "confidentiality",
    title: "What is private, and where that ends",
    body:
      "What you write is stored on your account and is not shared with anyone else. Two limits, stated " +
      "plainly rather than buried: a small number of people who build this can access accounts to fix " +
      "problems, and if something you write suggests you are in danger, a person here may see that part " +
      "of it. Nothing you say is sold, and nothing is used to advertise to you.",
  },
  {
    key: "crisis",
    title: "What happens if you write something that sounds like danger",
    body:
      "The software watches for language about being in danger. If it sees some, it will say so, it will " +
      "point you at a real human being who can help today, and it will keep talking to you. It is not a " +
      "trapdoor: you will not be locked out, reported, or handed off for saying a hard thing out loud.",
  },
  {
    key: "revoke",
    title: "You can stop this at any time",
    body:
      "You can withdraw this at any point, and you can ask for everything stored about you to be deleted. " +
      "Neither one requires a reason, and neither one closes the door on coming back.",
  },
] as const;

/** The 18+ gate. Its own attestation, stored on the row, never inferred. */
export const INTEGRATION_AGE_ATTESTATION = "I am 18 or older.";

/**
 * What the screen writes. Exported so the write path and any test agree on the
 * shape without either one restating it.
 */
export function buildConsentRow(userId: string): {
  user_id: string;
  program: string;
  version: string;
  age_attested: boolean;
  disclosures: Record<string, string>;
} {
  return {
    user_id: userId,
    program: "integration",
    version: INTEGRATION_CONSENT_VERSION,
    // Only ever written from a screen where the attestation was checked; the
    // column exists so the row can never be silent about it.
    age_attested: true,
    // The titles they were actually shown, keyed. A later revision can change
    // the set without a migration, and an old row still says what it said.
    disclosures: Object.fromEntries(INTEGRATION_DISCLOSURES.map((d) => [d.key, d.title])),
  };
}
